// Step1: テーブル作成 //
-- ロールの指定
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;

// Step2: 各種オブジェクトの作成 //
-- データベースの作成
CREATE OR REPLACE DATABASE AVALANCHE_DB;
-- スキーマの作成
CREATE OR REPLACE SCHEMA AVALANCHE_DB.AVALANCHE_SCHEMA;
-- スキーマの指定
USE AVALANCHE_DB.AVALANCHE_SCHEMA;

-- ステージの作成
CREATE OR REPLACE STAGE AVALANCHE_DB.AVALANCHE_SCHEMA.FILE DIRECTORY = (ENABLE = TRUE);
